export const HOTDEALSLEFTBARSEARCH_SUCCESS = 'HOTDEALS_LEFTBAR_SEARCH_SUCCESS';
export const HOTDEALSLEFTBARSEARCH_ERROR = 'HOTDEALS_LEFTBAR_SEARCH_ERROR';

export const HOTDEALSLEFTBARWEEKSEARCH_SUCCESS = 'HOTDEALS_LEFTBAR_WEEK_SEARCH_SUCCESS';
export const HOTDEALSLEFTBARWEEKSEARCH_ERROR = 'HOTDEALS_LEFTBAR_WEEK_SEARCH_ERROR';

export const COURSESNEARMESEARCH_SUCCESS = 'COURSESNEARME_SEARCH_SUCCESS';
export const COURSESNEARMESEARCH_ERROR = 'COURSESNEARME_SEARCH_ERROR';

export const HOTDEALS_REVIEW_SORT = 'HOTDEALS_REVIEW_SORT';
export const HOTDEALS_NAME_SORT = 'HOTDEALS_NAME_SORT';
